[mypy]
python_version = 3.14
strict = true
warn_unused_configs = true
namespace_packages = true
explicit_package_bases = true
disallow_any_unimported = true
follow_imports = silent
extra_checks = true
show_error_codes = true
mypy_path = src
exclude_gitignore = true
