[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "fitz-utils"
dynamic = ["version"]
description = "Extra functions for use with pymupdf module"
authors = [{ name = "The Walnut AI" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "ftfy>=6.3.1",
  "numpy>=2.2.6",
  "pandas>=2.3.3",
  "pymupdf>=1.28.0",
]

[dependency-groups]
test = [
    "pytest>=9.1.1",
]
dev = [
  "fitz-utils[test]",
  "pre-commit>=4.6.0",
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"

[tool.hatch.build.targets.wheel]
packages = ["fitz_utils"]
